# 开发环境
spring:
  # mysql数据源
  datasource:
    url: jdbc:mysql://localhost:3306/blog?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

server:
  port: 8080  # 服务端口

logging:
  file:
    path: log/blog.log  # 日志生成目录
